# Generated by Django 4.0.6 on 2022-07-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlling', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductActuator',
        ),
    ]
