# Generated by Django 4.0.4 on 2022-04-26 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actuatorsaction',
            name='actuator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.actuator'),
        ),
        migrations.AddField(
            model_name='actuatorsaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.product'),
        ),
    ]
