# Generated by Django 4.0.4 on 2022-04-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductActustor',
            new_name='ProductActuator',
        ),
        migrations.RemoveField(
            model_name='productplant',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='productplant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cultivation_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='number_of_crops',
        ),
        migrations.RemoveField(
            model_name='product',
            name='plants',
        ),
        migrations.RemoveField(
            model_name='product',
            name='water_tank_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AlterField(
            model_name='product',
            name='password',
            field=models.CharField(default='KqotNWc', max_length=10),
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
        migrations.DeleteModel(
            name='ProductPlant',
        ),
    ]
