# Generated by Django 4.0.4 on 2022-04-27 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_rename_productactustor_productactuator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='password',
            field=models.CharField(default='gqt5l74', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_between_automated_action',
            field=models.TimeField(default=datetime.timedelta(seconds=600)),
        ),
    ]
