# Generated by Django 4.0.6 on 2022-07-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='password',
            field=models.CharField(default='6ZGAUlI', max_length=10),
        ),
    ]
