# Generated by Django 4.0.1 on 2022-02-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Greenhouses', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='token',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='password',
            field=models.CharField(default='H1RILJ8', max_length=10),
        ),
    ]
