# Generated by Django 4.0.3 on 2022-03-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Greenhouses', '0005_alter_greenhouse_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='automated_control',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='password',
            field=models.CharField(default='wBzwkVh', max_length=10),
        ),
    ]
