# Generated by Django 4.0.1 on 2022-02-20 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Greenhouses', '0004_greenhouse_token_alter_greenhouse_password'),
        ('Hardware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorvalues',
            name='greenhouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greenhouse_sensor_values', to='Greenhouses.greenhouse'),
        ),
    ]
