# Generated by Django 4.0.3 on 2022-03-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardware', '0002_alter_sensorvalues_greenhouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuatorsaction',
            name='is_automated_action',
            field=models.BooleanField(default=False),
        ),
    ]
